# Generated by Django 3.1.5 on 2021-09-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetailsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=10)),
                ('Contact_Number', models.IntegerField()),
                ('Address', models.CharField(max_length=100)),
                ('Landmark', models.CharField(max_length=20)),
                ('City', models.CharField(max_length=15)),
                ('State', models.CharField(max_length=15)),
                ('Zip', models.CharField(max_length=10)),
            ],
        ),
    ]
