# Generated by Django 3.1.5 on 2021-10-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDetailsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_Name', models.CharField(max_length=100)),
                ('Book_Price', models.IntegerField()),
                ('Standard', models.IntegerField()),
                ('Book_Image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
